sonar.projectKey=Felipecoder07_avalie-papai
sonar.organization=felipecoder07

# Nome e versão exibidos na interface do SonarCloud
sonar.projectName=avalie-papai
sonar.projectVersion=1.0

# Caminhos de código-fonte e exclusões de diretórios compilados / dependências / documentação
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/uploads/**,**/docs/**,**/scripts/**,**/*.test.js,**/*.test.ts,**/*.test.tsx

# Codificação
sonar.sourceEncoding=UTF-8
